CREATE SEQUENCE IF NOT EXISTS eb_role2role_id_seq START 1;

CREATE SEQUENCE IF NOT EXISTS eb_role2permission_id_seq START 1;

CREATE SEQUENCE IF NOT EXISTS eb_role2user_id_seq START 1;

CREATE SEQUENCE IF NOT EXISTS eb_roles_id_seq START 100;

CREATE SEQUENCE IF NOT EXISTS eb_user2usergroup_id_seq START 1;

CREATE SEQUENCE IF NOT EXISTS eb_usergroup_id_seq START 1;

CREATE SEQUENCE IF NOT EXISTS eb_users_id_seq START 1;

