BEGIN
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_objects_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_objects_relations_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_objects_status_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_objects_ver_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_applications_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_objects2application_id_seq START WITH 1';
END;