//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressBase.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressBase.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- FUNCTION: public.eb_authenticateuser(text, text, text)
        ///
        ///-- DROP FUNCTION public.eb_authenticateuser(text, text, text);
        ///
        ///CREATE OR REPLACE FUNCTION public.eb_authenticateuser(
        ///	uname text,
        ///	passwrd text,
        ///	_socialid text)
        ///    RETURNS TABLE(userid integer, email text, firstname text, profileimage text, prolink text, roles_a text, rolename_a text, permissions text, loginattempts integer) 
        ///    LANGUAGE &apos;plpgsql&apos;
        ///AS $BODY$
        ///
        ///DECLARE userid INTEGER;
        ///DECLARE email TEXT;
        ///DECLARE firstname TEXT;
        ///DECL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SEQUENCE IF NOT EXISTS eb_role2role_id_seq START 1;
        ///
        ///-- Table: public.eb_role2role
        ///
        ///-- DROP TABLE public.eb_role2role;
        ///
        ///CREATE TABLE public.eb_role2role
        ///(
        ///    id integer NOT NULL DEFAULT nextval(&apos;eb_role2role_id_seq&apos;::regclass),
        ///    role1_id integer,
        ///    role2_id integer,
        ///    eb_del boolean DEFAULT false,
        ///    createdby integer,
        ///    createdat timestamp without time zone,
        ///    revokedby integer,
        ///    revokedat timestamp without time zone,
        ///    CONSTRAINT eb_role2role_id_pkey PRIMARY KEY (i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string postgres_eb_users {
            get {
                return ResourceManager.GetString("postgres_eb_users", resourceCulture);
            }
        }
    }
}
