--........eb_objects...............
CREATE SEQUENCE IF NOT EXISTS eb_objects_id_seq START 1;

--...........eb_objects_relations...............
CREATE SEQUENCE IF NOT EXISTS eb_objects_relations_id_seq START 1;

--.............eb_objects_status...............
CREATE SEQUENCE IF NOT EXISTS eb_objects_status_id_seq START 1;

--................eb_objects_ver................
CREATE SEQUENCE IF NOT EXISTS eb_objects_ver_id_seq START 1;

--.............eb_applications.....................
CREATE SEQUENCE IF NOT EXISTS eb_applications_id_seq START 1;