BEGIN
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_role2role_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_role2permission_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_role2user_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_roles_id_seq START WITH 100';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_user2usergroup_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_usergroup_id_seq START WITH 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE eb_users_id_seq START WITH 1';
END;

